sudo: required
dist: trusty
language: cpp
compiler: gcc
os: linux

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libgtkmm-3.0-dev libcppunit-dev liblog4cpp5-dev libgoocanvasmm-2.0-dev libxml++2.6-dev

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - make test
