sudo: false
language: cpp
compiler: gcc
os: linux

addons:
  apt:
    packages:
      - libgtkmm-3.0-dev
      - libcppunit-dev
      - liblog4cpp5-dev

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - make test
