#ifndef BLUESJACKRABBIT_SERVER_CONSTANTS_H
#define BLUESJACKRABBIT_SERVER_CONSTANTS_H


#define MESSAGE_HEADER_LENGTH 0xFFFFFFFF  // 4 bytes


#define HELLO_MSG_LENGTH 0xFF  // 1 byte hello message

#define LEFT 0x1
#define RIGHT 0x2
#define DOWN 0x3
#define UP 0x4


#endif /* BLUESJACKRABBIT_SERVER_CONSTANTS_H */
