#ifndef BLUESJACKRABBIT_EDITOR_EDITORLAYER_H
#define BLUESJACKRABBIT_EDITOR_EDITORLAYER_H

typedef enum layer
{
  PARALLAX,
  TILEMAP,
  OBJECTS,
  CONTROLS
} EditorLayer;

#endif // BLUESJACKRABBIT_EDITOR_EDITORLAYER_H